name: THE BEAUTIFUL CRIME
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e0f31'
    - '#31426e'
    - '#eb7d3b'
    - '#9b5c59'
    - '#68a7b9'
  brandStrength: 0.5625
  lightness: 0.125
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
